const reviewsData = {

  reviewsMeta: {
    product_id: '18078',
    ratings: {
      1: '7',
      2: '12',
      3: '9',
      4: '11',
      5: '21',
      6: '1',
    },
    recommended: {
      false: '29',
      true: '32',
    },
    characteristics: {
      Fit: {
        id: 60618,
        value: '2.7727272727272727',
      },
      Length: {
        id: 60619,
        value: '2.8260869565217391',
      },
      Comfort: {
        id: 60620,
        value: '2.9090909090909091',
      },
      Quality: {
        id: 60621,
        value: '2.7142857142857143',
      },
    },
  },
  productId: '18078',
  product: 'Camo Onesie',
  reviewList: {
    product: '18078',
    page: 0,
    count: 100,
    results: [
      {
        review_id: 288498,
        rating: 5,
        summary: 'Best hoodie of my life',
        recommend: true,
        response: null,
        body: 'What more can I say this hoodie absolutely rules',
        date: '2021-03-09T00:00:00.000Z',
        reviewer_name: 'ted',
        helpfulness: 25,
        photos: [],
      },
      {
        review_id: 348101,
        rating: 5,
        summary: 'This is the most magical product ever',
        recommend: true,
        response: null,
        body: "Here's the story of a lovely lady Who was bringing up three very lovely girls All of them had hair of gold, like their mother, The youngest one in curls Here's the story, of a man named Brady, Who was busy with three boys of his own, They were four men, living all together, Yet they were all alone 'Till the one day when the lady met this fellow And they knew it was much more than a…",
        date: '2021-04-25T00:00:00.000Z',
        reviewer_name: 'KimSoko',
        helpfulness: 21,
        photos: [],
      },
      {
        review_id: 348391,
        rating: 1,
        summary: 'bad',
        recommend: false,
        response: null,
        body: 'horrible horrible horrible horrible horrible horrible ',
        date: '2021-04-29T00:00:00.000Z',
        reviewer_name: 'mean reviewer',
        helpfulness: 9,
        photos: [],
      },
      {
        review_id: 348387,
        rating: 4,
        summary: 'decent',
        recommend: true,
        response: null,
        body: 'decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent decent ',
        date: '2021-04-29T00:00:00.000Z',
        reviewer_name: 'decent',
        helpfulness: 8,
        photos: [],
      },
      {
        review_id: 288815,
        rating: 3,
        summary: 'sdsdsdsdsd',
        recommend: false,
        response: null,
        body: 'asdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdsadsad',
        date: '2021-03-12T00:00:00.000Z',
        reviewer_name: 'asdassads',
        helpfulness: 8,
        photos: [
          {
            id: 496693,
            url: 'https://images.unsplash.com/photo-1611095567319-2f4c389168a9?ixid=MXwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1502&q=80',
          },
        ],
      },
      {
        review_id: 348289,
        rating: 1,
        summary: 'This camo onesie gives me a headache',
        recommend: false,
        response: null,
        body: 'I really hope this post request works.... etc etc etc etc etc etc etc ',
        date: '2021-04-28T00:00:00.000Z',
        reviewer_name: 'who is it',
        helpfulness: 7,
        photos: [],
      },
      {
        review_id: 288611,
        rating: 5,
        summary: 'A fantastic hoodie if you ask me',
        recommend: true,
        response: null,
        body: "It's so good I've written 5 reviews about it",
        date: '2021-03-10T00:00:00.000Z',
        reviewer_name: 'Jimbothy',
        helpfulness: 7,
        photos: [],
      },
      {
        review_id: 288814,
        rating: 5,
        summary: 'Oh yes this is good',
        recommend: true,
        response: null,
        body: 'sdasdsadasdasdsadasdsadsadsadsadasdasdasdsadsadsadsadasd',
        date: '2021-03-12T00:00:00.000Z',
        reviewer_name: 'dsdsdsd',
        helpfulness: 5,
        photos: [
          {
            id: 496692,
            url: 'https://images.unsplash.com/photo-1554260570-9140fd3b7614?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80',
          },
        ],
      },
      {
        review_id: 348290,
        rating: 4,
        summary: 'Pretty good',
        recommend: true,
        response: null,
        body: "Pretty decent. Does the trick..... keeps you warm. Isn't the most fashion forward though.",
        date: '2021-04-28T00:00:00.000Z',
        reviewer_name: 'who is it?',
        helpfulness: 4,
        photos: [],
      },
      {
        review_id: 348366,
        rating: 3,
        summary: 'testing testing 123',
        recommend: true,
        response: null,
        body: 'this review body is long enough to pass the character restrictions',
        date: '2021-04-29T00:00:00.000Z',
        reviewer_name: 'who',
        helpfulness: 2,
        photos: [],
      },
      {
        review_id: 348411,
        rating: 3,
        summary: 'testing photo upload',
        recommend: true,
        response: null,
        body: 'are these photos uploading? i hope they are! fingers crossed!',
        date: '2021-04-29T00:00:00.000Z',
        reviewer_name: 'who is it',
        helpfulness: 1,
        photos: [
          {
            id: 614397,
            url: 'C:\\fakepath\\Orange Collar Girl.jpeg',
          },
          {
            id: 614398,
            url: 'C:\\fakepath\\171433724_280540490213697_8011510587583643817_n.jpeg',
          },
          {
            id: 614399,
            url: 'C:\\fakepath\\Light Blue Girl.jpeg',
          },
          {
            id: 614400,
            url: 'C:\\fakepath\\Dark Blue.jpeg',
          },
          {
            id: 614401,
            url: 'C:\\fakepath\\Dark Pink Girl.jpeg',
          },
        ],
      },
      {
        review_id: 348288,
        rating: 3,
        summary: 'I hope this works',
        recommend: true,
        response: null,
        body: 'I hope this works  is this enough characters blah blah blah blah blah is this enough characters blah blah blah blah blah',
        date: '2021-04-28T00:00:00.000Z',
        reviewer_name: 'hello',
        helpfulness: 1,
        photos: [],
      },
      {
        review_id: 347996,
        rating: 5,
        summary: "This is the best darn product I've ever seen",
        recommend: true,
        response: null,
        body: 'Again, so great. Like so so great',
        date: '2021-04-20T00:00:00.000Z',
        reviewer_name: 'This is my name',
        helpfulness: 1,
        photos: [],
      },
      {
        review_id: 289044,
        rating: 1,
        summary: 'title',
        recommend: true,
        response: null,
        body: 'body',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'user',
        helpfulness: 1,
        photos: [],
      },
      {
        review_id: 288800,
        rating: 5,
        summary: 'I finally figured out how to scream',
        recommend: true,
        response: null,
        body: 'kalfosahgoihjoithnweriogtnwoiagnwioginowaghoiwahgoiwahbgiowhgi!!!',
        date: '2021-03-11T00:00:00.000Z',
        reviewer_name: 'aggasasg',
        helpfulness: 1,
        photos: [],
      },
      {
        review_id: 288806,
        rating: 5,
        summary: 'This hoodie makes me feel so fly that I can fly.......zerrrp',
        recommend: true,
        response: null,
        body: 'I am superman, the jam, the man with the plan, I am ryman, to the beat of 50 characters per body deet da deet.',
        date: '2021-03-12T00:00:00.000Z',
        reviewer_name: 'coolio',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 348382,
        rating: 4,
        summary: "Yahoo we're almost done",
        recommend: false,
        response: null,
        body: 'hendrerit gravida rutrum quisque non tellus orci ac auctor augue mauris augue neque gravida in fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam id leo in vitae turpis massa sed elementum tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse in',
        date: '2021-04-29T00:00:00.000Z',
        reviewer_name: 'WhoCares',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 289020,
        rating: 3,
        summary: 'THIS IS A TEST JIM',
        recommend: false,
        response: null,
        body: 'fesfdsf d',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'Taylor Smart',
        helpfulness: 0,
        photos: [
          {
            id: 496760,
            url: 'C:\\fakepath\\Headshot (copy).jpg',
          },
          {
            id: 496761,
            url: 'C:\\fakepath\\Headshot.jpg',
          },
          {
            id: 496762,
            url: 'C:\\fakepath\\Error Runner js.png',
          },
        ],
      },
      {
        review_id: 289018,
        rating: 2,
        summary: 'testfe',
        recommend: false,
        response: null,
        body: 'ceseff',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'Taylor Smart',
        helpfulness: 0,
        photos: [
          {
            id: 496759,
            url: 'C:\\fakepath\\Headshot.jpg',
          },
        ],
      },
      {
        review_id: 289016,
        rating: 2,
        summary: 'Title',
        recommend: false,
        response: null,
        body: 'fesfesef',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'Taylor Smart',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 348178,
        rating: 3,
        summary: 'This was a dud',
        recommend: false,
        response: null,
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida tortor sem, nec scelerisque enim pharetra id. Vestibulum et velit dolor. Donec hendrerit est nec ornare pharetra. Cras ut est a sem vehicula imperdiet eget in dolor. Donec ligula.',
        date: '2021-04-27T00:00:00.000Z',
        reviewer_name: 'Hater123',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 289013,
        rating: 3,
        summary: 'THIS IS A TEST JIM',
        recommend: false,
        response: null,
        body: 'feswcfe cf eswef',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'Taylor Smart',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 289012,
        rating: 2,
        summary: 'testeeer fdfd',
        recommend: false,
        response: null,
        body: 'fesefs',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'Taylor Smart',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 289011,
        rating: 2,
        summary: 'fe',
        recommend: false,
        response: null,
        body: 'fdsfasdfa',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'Taylor Smart',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 289002,
        rating: 2,
        summary: 'THIS IS A TEST JIM',
        recommend: false,
        response: null,
        body: 'fescfec ec se',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'Taylor Smart',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 348100,
        rating: 5,
        summary: "Let's do this again",
        recommend: true,
        response: null,
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut justo et leo sagittis convallis posuere nec quam. Nulla efficitur dictum nibh eget consectetur. Quisque vehicula pretium laoreet. Aenean ut erat ullamcorper, sodales ante sit amet, luctus nisi. Sed pretium erat dignissim orci tempus, in cursus ipsum tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis ex ac sapien sodales mattis et vel leo. Nunc quis imperdiet velit, sed porta turpis. Phasellus vitae massa ullamcorper, interdum purus eget, mollis lectus. Maecenas est lacus, efficitur a nunc in biam.',
        date: '2021-04-25T00:00:00.000Z',
        reviewer_name: 'KimSoko',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 288838,
        rating: 2,
        summary: 'tewst',
        recommend: false,
        response: null,
        body: 'fesfesef',
        date: '2021-03-12T00:00:00.000Z',
        reviewer_name: 'Taylor Smart',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 288820,
        rating: 4,
        summary: 'If this test works itll be insane',
        recommend: true,
        response: null,
        body: 'kjsdakljsadkjlsadkljdsakljsdakskskjdskjldsalkjasdkljsdsdksadkjdsakljsadjklsad',
        date: '2021-03-12T00:00:00.000Z',
        reviewer_name: 'jim',
        helpfulness: 0,
        photos: [
          {
            id: 496694,
            url: 'https://images.unsplash.com/photo-1615486761936-d82f225dfa2a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80',
          },
          {
            id: 496695,
            url: 'https://images.unsplash.com/photo-1611095567319-2f4c389168a9?ixid=MXwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1502&q=80',
          },
        ],
      },
      {
        review_id: 289112,
        rating: 6,
        summary: 'title',
        recommend: true,
        response: null,
        body: 'body',
        date: '2021-03-14T00:00:00.000Z',
        reviewer_name: 'user',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 289111,
        rating: 1,
        summary: 'title',
        recommend: true,
        response: null,
        body: 'body',
        date: '2021-03-14T00:00:00.000Z',
        reviewer_name: 'username',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 289102,
        rating: 1,
        summary: 'hello',
        recommend: false,
        response: null,
        body: 'Body',
        date: '2021-03-14T00:00:00.000Z',
        reviewer_name: 'user',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 288810,
        rating: 3,
        summary: 'SINGING IN THE RAIN',
        recommend: false,
        response: null,
        body: "SINGING IN THE RAIN. OH WHAT A WONDERFUL DAY!!! I'M SINGING IN THE RAIN!",
        date: '2021-03-12T00:00:00.000Z',
        reviewer_name: 'SAGASD',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 288803,
        rating: 5,
        summary: "WHAT ARE THESE CHARACTERISTIC_ID'S CALLED",
        recommend: true,
        response: null,
        body: 'Oh sorry am I yelling?shdhjgjfgjfgjfgjfgjdhjkgdhkghkhgklguyluyhlufhyluyilyfgul;fgyil;',
        date: '2021-03-11T00:00:00.000Z',
        reviewer_name: 'agdghgh',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 288802,
        rating: 5,
        summary: 'I finally figured out how to speak up ',
        recommend: true,
        response: null,
        body: 'ajfogjhaosighwioghoiwarngoiawrngoiwarehngioawhngioaewhngionahrewiog',
        date: '2021-03-11T00:00:00.000Z',
        reviewer_name: 'oagios',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 289052,
        rating: 5,
        summary: 'its working',
        recommend: true,
        response: null,
        body: 'ITS ALIVE! MY BEAUTIFUL CREATION IS ALIVE!',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'ITS WORKING',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 289043,
        rating: 2,
        summary: 'cd',
        recommend: false,
        response: null,
        body: 'css',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'Taylor Smart',
        helpfulness: 0,
        photos: [
          {
            id: 496773,
            url: 'C:\\fakepath\\Headshot.jpg',
          },
        ],
      },
      {
        review_id: 289034,
        rating: 2,
        summary: 'fffeee',
        recommend: false,
        response: null,
        body: 'fffdsss',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'Taylor Smart',
        helpfulness: 0,
        photos: [
          {
            id: 496771,
            url: 'C:\\fakepath\\Headshot.jpg',
          },
        ],
      },
      {
        review_id: 289033,
        rating: 2,
        summary: 'fews',
        recommend: false,
        response: null,
        body: 'fdsfes',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'Taylor Smart',
        helpfulness: 0,
        photos: [
          {
            id: 496770,
            url: 'C:\\fakepath\\Headshot.jpg',
          },
        ],
      },
    ],
  },

};

export default reviewsData;
